# Karaf fearture Google libraries

image::https://github.com/BlackBeltTechnology/karaf-features-google/actions/workflows/build.yml/badge.svg?branch=develop[link="https://github.com/BlackBeltTechnology/karaf-features-google/actions/workflows/build.yml" float="center"]

Externsion to karaf which adds Google libraries bundles to karaf features.

To install some features features required. Please add the folloeing repository to your distribution (versions can be different, the tested versions are presented): 

- mvn:org.apache.cxf.karaf/apache-cxf/3.3.1/xml/features 
- mvn:hu.blackbelt.karaf.features/apache-httpclient/1.0.0/xml/features (Github: https://github.com/BlackBeltTechnology/karaf-features-apache-httpclient)


## Features:
- jimfs 1.1
- guava 20
- guava 21
- guava 22
- guava 23
- guava 24
- guava 25
- guava 26
- guava 27
- guava 28
- guava 29
- guava 30
- guava 31
- guice 3.0
- guice 4.0
- guice 5.0
- gson 2.1
- google-api-client 1.23.0
- google-api-services-oauth2 1.23.0
- google-api-services-calendar 1.23.0
- google-gdata 1.47.1.1

== Contributing to the project

Everyone is welcome to contribute to karaf-features-google! As a starter, please read the corresponding link:CONTRIBUTING.adoc[CONTRIBUTING] guide for details!


== License

This project is licensed under the https://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0].
