# Karaf feature apache commons

image::https://github.com/BlackBeltTechnology/karaf-features-apache-commons/actions/workflows/build.yml/badge.svg?branch=develop[link="https://github.com/BlackBeltTechnology/karaf-features-apache-commons/actions/workflows/build.yml" float="center"]

Externsion to karaf which adds Apache Commons bundles to karaf features.


## Features:

- apache-commons-beanutils 1.9.2
- apache-commons-collections 3.2.2
- apache-commons-collections4 4.3
- apache-commons-io 2.6
- apache-commons-pool 1.6 
- apache-commons-pool2 2.4.1 
- apache-commons-dbcp2 2.1.1
- apache-commons-codec 1.12
- apache-commons-fileupload 1.3.1
- apache-commons-lang 2.6 
- apache-commons-logging 1.1.1 
- apache-commons-configuraton 1.10 
- apache-commons-math3 3.6.1
- apache-commons-math 2.2
- apache-commons-lang2 3.6
- apache-commons-csv 1.6 
- apache-commons-compress 1.18 
- apache-commons-bcel 5.2
- apache-xmlbeans2 2.6.0
- apache-jexl3 3.1

== Contributing to the project

Everyone is welcome to contribute to karaf-features-apache-commons! As a starter, please read the corresponding link:CONTRIBUTING.adoc[CONTRIBUTING] guide for details!


== License

This project is licensed under the https://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0].
