# Karaf feature Eclipse Epsilon

image::https://github.com/BlackBeltTechnology/karaf-features-eclipse-epsilon/actions/workflows/build.yml/badge.svg?branch=develop[link="https://github.com/BlackBeltTechnology/karaf-features-eclipse-epsilon/actions/workflows/build.yml" float="center"]


Externsion to karaf which adds BouncyCastle bundles to karaf features.

Externsion to karaf which adds Eclipse Epsilon bundles to karaf features.

To install some features features required. Please add the folloeing repository to your distribution (versions can be different, the tested versions are presented): 

- mvn:hu.blackbelt.karaf.features/bouncycastle/2.0.0/xml/features (Github: https://github.com/BlackBeltTechnology/karaf-features-bouncycastle)
- mvn:hu.blackbelt.karaf.features/antlr/2.0.0/xml/features (Github: https://github.com/BlackBeltTechnology/karaf-features-antlr)
- mvn:hu.blackbelt.karaf.features/apache-commons/2.0.0/xml/features (Github: https://github.com/BlackBeltTechnology/karaf-features-apache-commons)
- mvn:hu.blackbelt.karaf.features/apache-httpclient/2.0.0/xml/features (Github: https://github.com/BlackBeltTechnology/karaf-features-apache-httpclient)
- mvn:hu.blackbelt.karaf.features/apache-poi/2.0.0/xml/features (Github: https://github.com/BlackBeltTechnology/karaf-features-apache-poi)
- mvn:hu.blackbelt.karaf.features/google/2.0.0/xml/features (Github: https://github.com/BlackBeltTechnology/karaf-features-google)
- mvn:hu.blackbelt.karaf.features/eclipse-emf/2.0.0/xml/features (Github: https://github.com/BlackBeltTechnology/karaf-features-eclipse-emf)

## Features:

- eclipse-epsilon 2.4.0


== Contributing to the project

Everyone is welcome to contribute to karaf-features-eclipse-epsilon! As a starter, please read the corresponding link:CONTRIBUTING.adoc[CONTRIBUTING] guide for details!


== License

This project is licensed under the https://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0].
