# Karaf fearture BouncyCastle

image::https://github.com/BlackBeltTechnology/karaf-features-jxls/actions/workflows/build.yml/badge.svg?branch=develop[link="https://github.com/BlackBeltTechnology/karaf-features-jxls/actions/workflows/build.yml" float="center"]

To install some features features required. Please add the folloeing repository to your distribution (versions can be different, the tested versions are presented): 

- mvn:hu.blackbelt.karaf.features/bouncycastle/2.0.0/xml/features (Github: https://github.com/BlackBeltTechnology/karaf-features-bouncycastle)
- mvn:hu.blackbelt.karaf.features/apache-commons/2.0.0/xml/features (Github: https://github.com/BlackBeltTechnology/karaf-features-apache-commons)
- mvn:hu.blackbelt.karaf.features/apache-poi/2.0.0/xml/features (Github: https://github.com/BlackBeltTechnology/karaf-features-apache-poi)

There are not (yet) feature packed logback core dependency:
- mvn:ch.qos.logback/logback-core/1.2.3

## Features:
- jxls 2.6.0

== Contributing to the project

Everyone is welcome to contribute to karaf-features-jxls! As a starter, please read the corresponding link:CONTRIBUTING.adoc[CONTRIBUTING] guide for details!


== License

This project is licensed under the https://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0].
